#!/bin/zsh

USER_NAME="argon"
HOME_DIRECTORY="/home/$USER_NAME"
CODE_DIRECTORY="$HOME_DIRECTORY/code"
WORKING_DIRECTORY="$CODE_DIRECTORY/2-hello-world"
HOST_WORKING_DIRECTORY=$(pwd)/..
CERTIFICATE_DIRECTORY="$HOME/.ssh/"

docker run \
  -it \
  -v "$HOST_WORKING_DIRECTORY:$CODE_DIRECTORY" \
  -v "$CERTIFICATE_DIRECTORY:$HOME_DIRECTORY/.ssh:ro" \
  -w "$WORKING_DIRECTORY" \
  --rm "piotrjustyna/argon:1.2" "./entrypoint.sh" "$WORKING_DIRECTORY"